name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: '409.0.0'  # Specify the desired version of the Google Cloud SDK
        project_id: 'round-seeker-433011-t3'
        service_account_key: ${{ secrets.GCP_SA_KEY }}  # Your service account key

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Specify the desired Terraform version

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Get Instance IP
      id: get_instance_ip
      run: echo "INSTANCE_IP=$(terraform output -raw instance_ip)" >> $GITHUB_ENV

    - name: Use output value
      run: echo "The instance IP is ${{ env.INSTANCE_IP }}"
